services:
  bot:
    build: .
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./apps/pollux/.env
    environment:
      - DB_TYPE=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_SYNCHRONIZE=false
      - API_PORT=3025
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./apps/web/.env.local
    environment:
      - BOT_API_URL=http://127.0.0.1:3025
