services:
  bot:
    image: ghcr.io/sidiadevelopment/poex-bot:latest
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./apps/pollux/.env
    environment:
      - DB_TYPE=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_SYNCHRONIZE=false
      - API_PORT=3025
  web:
    image: ghcr.io/sidiadevelopment/poex-web:latest
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./apps/web/.env.local
    environment:
      - BOT_API_URL=http://127.0.0.1:3025
