import en from "./localizations/en"
import {LocalizationOverrides} from "@pollux/i18n"

declare module "@pollux/core/types" {
    type PoExchangeLocalizationType = typeof en
    export interface ILocalization extends PoExchangeLocalizationType {}

    export interface IConfig {
        poExchange?: {
            apiUrl?: string
            apiKey?: string
            connectUrl?: string
        }
    }
}

export enum PoExchangeChannelId {
    POE1_BOSS_KILLING = "POE1_BOSS_KILLING",
    POE1_NIGHTMARE_MAPS = "POE1_NIGHTMARE_MAPS",
    POE1_INVITATIONS = "POE1_INVITATIONS",
    POE1_BLOODLINES = "POE1_BLOODLINES",
    POE1_LABYRINTH = "POE1_LABYRINTH",
    POE1_5_WAY = "POE1_5_WAY",
    POE1_CAMPAIGN_SKIP = "POE1_CAMPAIGN_SKIP",
    POE1_GOLD_ROTATION = "POE1_GOLD_ROTATION",
    POE1_TEMPLE_HOST = "POE1_TEMPLE_HOST",
    POE1_CHALLENGE_COMPLETION = "POE1_CHALLENGE_COMPLETION",
    POE1_BENCH_CRAFT = "POE1_BENCH_CRAFT",
    POE1_STANDARD_BOSS_KILLING = "POE1_STD_BOSS_KILLING",
    POE1_STANDARD_NIGHTMARE_MAPS = "POE1_STD_NIGHTMARE_MAPS",
    POE1_STANDARD_INVITATIONS = "POE1_STD_INVITATIONS",
    POE1_STANDARD_BLOODLINES = "POE1_STD_BLOODLINES",
    POE1_STANDARD_LABYRINTH = "POE1_STD_LABYRINTH",
    POE1_STANDARD_5_WAY = "POE1_STD_5_WAY",
    POE1_STANDARD_CAMPAIGN_SKIP = "POE1_STD_CAMPAIGN_SKIP",
    POE1_STANDARD_GOLD_ROTATION = "POE1_STD_GOLD_ROTATION",
    POE1_STANDARD_TEMPLE_HOST = "POE1_STD_TEMPLE_HOST",
    POE1_STANDARD_CHALLENGE_COMPLETION = "POE1_STD_CHALLENGE_COMPLETION",
    POE1_STANDARD_BENCH_CRAFT = "POE1_STD_BENCH_CRAFT",
    POE2_PINNACLE_ENCOUNTERS = "POE2_PINNACLE_ENCOUNTERS",
    POE2_CITADEL_BOSSES = "POE2_CITADEL_BOSSES",
    POE2_ANOMALY_AND_MAP_BOSSES = "POE2_ANOMALY_AND_MAP_BOSSES",
    POE2_CAMPAIGN_BOSSES = "POE2_CAMPAIGN_BOSSES",
    POE2_CAMPAIGN_LEVELING = "POE2_CAMPAIGN_LEVELING",
    POE2_GOLD_ROTATION = "POE2_GOLD_ROTATION",
    POE2_CHALLENGE_COMPLETION = "POE2_CHALLENGE_COMPLETION",
    POE2_ASCENDANCY_TRIALS = "POE2_ASCENDANCY_TRIALS",
    POE2_CRAFTING_SERVICES = "POE2_CRAFTING_SERVICES",
    POE2_STANDARD_PINNACLE_ENCOUNTERS = "POE2_STD_PINNACLE_ENCOUNTERS",
    POE2_STANDARD_CITADEL_BOSSES = "POE2_STD_CITADEL_BOSSES",
    POE2_STANDARD_ANOMALY_AND_MAP_BOSSES = "POE2_STD_ANOMALY_AND_MAP_BOSSES",
    POE2_STANDARD_CAMPAIGN_BOSSES = "POE2_STD_CAMPAIGN_BOSSES",
    POE2_STANDARD_CAMPAIGN_LEVELING = "POE2_STD_CAMPAIGN_LEVELING",
    POE2_STANDARD_GOLD_ROTATION = "POE2_STD_GOLD_ROTATION",
    POE2_STANDARD_CHALLENGE_COMPLETION = "POE2_STD_CHALLENGE_COMPLETION",
    POE2_STANDARD_ASCENDANCY_TRIALS = "POE2_STD_ASCENDANCY_TRIALS",
    POE2_STANDARD_CRAFTING_SERVICES = "POE2_STD_CRAFTING_SERVICES"
}

export enum PoExchangeSettingsKeys {
    VouchChannel = "poex.vouchChannel",
    VouchEnabled = "poex.vouchEnabled"
}

export const PoExchangeLocalizations: LocalizationOverrides = {
    en
}
