export default {
    poex: {
        management: {
            settings: "Settings",
            channelMappings: "Channel Mappings",
            channelKey: "Category",
            channel: "Channel",
            vouchRoles: "Vouch Roles",
            role: "Role",
            threshold: "Vouches Required"
        },
        categories: {
            bossKilling: "Boss Killing",
            nightmareMaps: "Nightmare Maps",
            invitations: "Invitations",
            bloodlines: "Bloodlines",
            labyrinth: "Labyrinth",
            fiveWay: "5-Way",
            campaignSkip: "Campaign Skip",
            goldRotation: "Gold Rotation",
            templeHost: "Temple Host",
            challengeCompletion: "Challenge Completion",
            benchCraft: "Bench Craft",
            stdBossKilling: "Std Boss Killing",
            stdNightmareMaps: "Std Nightmare Maps",
            stdInvitations: "Std Invitations",
            stdBloodlines: "Std Bloodlines",
            stdLabyrinth: "Std Labyrinth",
            stdFiveWay: "Std 5-Way",
            stdCampaignSkip: "Std Campaign Skip",
            stdGoldRotation: "Std Gold Rotation",
            stdTempleHost: "Std Temple Host",
            stdChallengeCompletion: "Std Challenge Completion",
            stdBenchCraft: "Std Bench Craft",
            hcBossKilling: "HC Boss Killing",
            hcNightmareMaps: "HC Nightmare Maps",
            hcInvitations: "HC Invitations",
            hcBloodlines: "HC Bloodlines",
            hcLabyrinth: "HC Labyrinth",
            hcFiveWay: "HC 5-Way",
            hcCampaignSkip: "HC Campaign Skip",
            hcGoldRotation: "HC Gold Rotation",
            hcTempleHost: "HC Temple Host",
            hcChallengeCompletion: "HC Challenge Completion",
            hcBenchCraft: "HC Bench Craft",
            hcLeagueBossKilling: "HC League Boss Killing",
            hcLeagueNightmareMaps: "HC League Nightmare Maps",
            hcLeagueInvitations: "HC League Invitations",
            hcLeagueBloodlines: "HC League Bloodlines",
            hcLeagueLabyrinth: "HC League Labyrinth",
            hcLeagueFiveWay: "HC League 5-Way",
            hcLeagueCampaignSkip: "HC League Campaign Skip",
            hcLeagueGoldRotation: "HC League Gold Rotation",
            hcLeagueTempleHost: "HC League Temple Host",
            hcLeagueChallengeCompletion: "HC League Challenge Completion",
            hcLeagueBenchCraft: "HC League Bench Craft",
            wtbBossKilling: "WTB Boss Killing",
            wtbNightmareMaps: "WTB Nightmare Maps",
            wtbInvitations: "WTB Invitations",
            wtbBloodlines: "WTB Bloodlines",
            wtbLabyrinth: "WTB Labyrinth",
            wtbFiveWay: "WTB 5-Way",
            wtbCampaignSkip: "WTB Campaign Skip",
            wtbGoldRotation: "WTB Gold Rotation",
            wtbTempleHost: "WTB Temple Host",
            wtbChallengeCompletion: "WTB Challenge Completion",
            wtbBenchCraft: "WTB Bench Craft",
            wtbStdBossKilling: "WTB Std Boss Killing",
            wtbStdNightmareMaps: "WTB Std Nightmare Maps",
            wtbStdInvitations: "WTB Std Invitations",
            wtbStdBloodlines: "WTB Std Bloodlines",
            wtbStdLabyrinth: "WTB Std Labyrinth",
            wtbStdFiveWay: "WTB Std 5-Way",
            wtbStdCampaignSkip: "WTB Std Campaign Skip",
            wtbStdGoldRotation: "WTB Std Gold Rotation",
            wtbStdTempleHost: "WTB Std Temple Host",
            wtbStdChallengeCompletion: "WTB Std Challenge Completion",
            wtbStdBenchCraft: "WTB Std Bench Craft",
            wtbHcBossKilling: "WTB HC Boss Killing",
            wtbHcNightmareMaps: "WTB HC Nightmare Maps",
            wtbHcInvitations: "WTB HC Invitations",
            wtbHcBloodlines: "WTB HC Bloodlines",
            wtbHcLabyrinth: "WTB HC Labyrinth",
            wtbHcFiveWay: "WTB HC 5-Way",
            wtbHcCampaignSkip: "WTB HC Campaign Skip",
            wtbHcGoldRotation: "WTB HC Gold Rotation",
            wtbHcTempleHost: "WTB HC Temple Host",
            wtbHcChallengeCompletion: "WTB HC Challenge Completion",
            wtbHcBenchCraft: "WTB HC Bench Craft",
            wtbHcLeagueBossKilling: "WTB HC League Boss Killing",
            wtbHcLeagueNightmareMaps: "WTB HC League Nightmare Maps",
            wtbHcLeagueInvitations: "WTB HC League Invitations",
            wtbHcLeagueBloodlines: "WTB HC League Bloodlines",
            wtbHcLeagueLabyrinth: "WTB HC League Labyrinth",
            wtbHcLeagueFiveWay: "WTB HC League 5-Way",
            wtbHcLeagueCampaignSkip: "WTB HC League Campaign Skip",
            wtbHcLeagueGoldRotation: "WTB HC League Gold Rotation",
            wtbHcLeagueTempleHost: "WTB HC League Temple Host",
            wtbHcLeagueChallengeCompletion: "WTB HC League Challenge Completion",
            wtbHcLeagueBenchCraft: "WTB HC League Bench Craft",
            poe2PinnacleEncounters: "PoE2 Pinnacle Encounters",
            poe2CitadelBosses: "PoE2 Citadel Bosses",
            poe2AnomalyAndMapBosses: "PoE2 Anomaly & Map Bosses",
            poe2CampaignBosses: "PoE2 Campaign Bosses",
            poe2CampaignSkip: "PoE2 Campaign Skip",
            poe2GoldRotation: "PoE2 Gold Rotation",
            poe2ChallengeCompletion: "PoE2 Challenge Completion",
            poe2AscendancyTrials: "PoE2 Ascendancy Trials",
            poe2CraftingServices: "PoE2 Crafting Services",
            poe2StdPinnacleEncounters: "PoE2 Std Pinnacle Encounters",
            poe2StdCitadelBosses: "PoE2 Std Citadel Bosses",
            poe2StdAnomalyAndMapBosses: "PoE2 Std Anomaly & Map Bosses",
            poe2StdCampaignBosses: "PoE2 Std Campaign Bosses",
            poe2StdCampaignSkip: "PoE2 Std Campaign Skip",
            poe2StdGoldRotation: "PoE2 Std Gold Rotation",
            poe2StdChallengeCompletion: "PoE2 Std Challenge Completion",
            poe2StdAscendancyTrials: "PoE2 Std Ascendancy Trials",
            poe2StdCraftingServices: "PoE2 Std Crafting Services",
            poe2HcPinnacleEncounters: "PoE2 HC Pinnacle Encounters",
            poe2HcCitadelBosses: "PoE2 HC Citadel Bosses",
            poe2HcAnomalyAndMapBosses: "PoE2 HC Anomaly & Map Bosses",
            poe2HcCampaignBosses: "PoE2 HC Campaign Bosses",
            poe2HcCampaignSkip: "PoE2 HC Campaign Skip",
            poe2HcGoldRotation: "PoE2 HC Gold Rotation",
            poe2HcChallengeCompletion: "PoE2 HC Challenge Completion",
            poe2HcAscendancyTrials: "PoE2 HC Ascendancy Trials",
            poe2HcCraftingServices: "PoE2 HC Crafting Services",
            poe2HcLeaguePinnacleEncounters: "PoE2 HC League Pinnacle Encounters",
            poe2HcLeagueCitadelBosses: "PoE2 HC League Citadel Bosses",
            poe2HcLeagueAnomalyAndMapBosses: "PoE2 HC League Anomaly & Map Bosses",
            poe2HcLeagueCampaignBosses: "PoE2 HC League Campaign Bosses",
            poe2HcLeagueCampaignSkip: "PoE2 HC League Campaign Skip",
            poe2HcLeagueGoldRotation: "PoE2 HC League Gold Rotation",
            poe2HcLeagueChallengeCompletion: "PoE2 HC League Challenge Completion",
            poe2HcLeagueAscendancyTrials: "PoE2 HC League Ascendancy Trials",
            poe2HcLeagueCraftingServices: "PoE2 HC League Crafting Services",
            poe2WtbPinnacleEncounters: "PoE2 WTB Pinnacle Encounters",
            poe2WtbCitadelBosses: "PoE2 WTB Citadel Bosses",
            poe2WtbAnomalyAndMapBosses: "PoE2 WTB Anomaly & Map Bosses",
            poe2WtbCampaignBosses: "PoE2 WTB Campaign Bosses",
            poe2WtbCampaignSkip: "PoE2 WTB Campaign Skip",
            poe2WtbGoldRotation: "PoE2 WTB Gold Rotation",
            poe2WtbChallengeCompletion: "PoE2 WTB Challenge Completion",
            poe2WtbAscendancyTrials: "PoE2 WTB Ascendancy Trials",
            poe2WtbCraftingServices: "PoE2 WTB Crafting Services",
            poe2WtbStdPinnacleEncounters: "PoE2 WTB Std Pinnacle Encounters",
            poe2WtbStdCitadelBosses: "PoE2 WTB Std Citadel Bosses",
            poe2WtbStdAnomalyAndMapBosses: "PoE2 WTB Std Anomaly & Map Bosses",
            poe2WtbStdCampaignBosses: "PoE2 WTB Std Campaign Bosses",
            poe2WtbStdCampaignSkip: "PoE2 WTB Std Campaign Skip",
            poe2WtbStdGoldRotation: "PoE2 WTB Std Gold Rotation",
            poe2WtbStdChallengeCompletion: "PoE2 WTB Std Challenge Completion",
            poe2WtbStdAscendancyTrials: "PoE2 WTB Std Ascendancy Trials",
            poe2WtbStdCraftingServices: "PoE2 WTB Std Crafting Services",
            poe2WtbHcPinnacleEncounters: "PoE2 WTB HC Pinnacle Encounters",
            poe2WtbHcCitadelBosses: "PoE2 WTB HC Citadel Bosses",
            poe2WtbHcAnomalyAndMapBosses: "PoE2 WTB HC Anomaly & Map Bosses",
            poe2WtbHcCampaignBosses: "PoE2 WTB HC Campaign Bosses",
            poe2WtbHcCampaignSkip: "PoE2 WTB HC Campaign Skip",
            poe2WtbHcGoldRotation: "PoE2 WTB HC Gold Rotation",
            poe2WtbHcChallengeCompletion: "PoE2 WTB HC Challenge Completion",
            poe2WtbHcAscendancyTrials: "PoE2 WTB HC Ascendancy Trials",
            poe2WtbHcCraftingServices: "PoE2 WTB HC Crafting Services",
            poe2WtbHcLeaguePinnacleEncounters: "PoE2 WTB HC League Pinnacle Encounters",
            poe2WtbHcLeagueCitadelBosses: "PoE2 WTB HC League Citadel Bosses",
            poe2WtbHcLeagueAnomalyAndMapBosses: "PoE2 WTB HC League Anomaly & Map Bosses",
            poe2WtbHcLeagueCampaignBosses: "PoE2 WTB HC League Campaign Bosses",
            poe2WtbHcLeagueCampaignSkip: "PoE2 WTB HC League Campaign Skip",
            poe2WtbHcLeagueGoldRotation: "PoE2 WTB HC League Gold Rotation",
            poe2WtbHcLeagueChallengeCompletion: "PoE2 WTB HC League Challenge Completion",
            poe2WtbHcLeagueAscendancyTrials: "PoE2 WTB HC League Ascendancy Trials",
            poe2WtbHcLeagueCraftingServices: "PoE2 WTB HC League Crafting Services"
        },
        settings: {
            vouchEnabled: "Enable the vouch button on service messages",
            vouchChannel: "Channel where vouch messages are posted"
        },
        vouch: {
            button: "Vouch",
            notConfigured: "Vouch service is not configured.",
            noLinkedAccount: "Could not process vouch: the user has no linked account.",
            userNotFound: "Could not find user: the user has no linked account.",
            linkDiscord: "They can link it here",
            success: "Vouch registered!",
            vouchSaved: "Vouch saved! The user has {amount} pending vouch(es) that will be attributed once they link their Discord account.",
            uniqueVouches: "Unique Vouches",
            cycleVouches: "Cycle Vouches",
            currentCycle: "Current cycle",
            totalVouches: "Total Vouches",
            discordLinked: "Discord Linked",
            discordAccountAge: "Account Age",
            discordJoinDate: "Joined Server",
            memberSince: "PoExchange member since",
            yes: "Yes",
            no: "No",
            selfVouch: "You cannot vouch for yourself.",
            countFailed: "Could not request vouches.",
            countNoUser: "Could not request vouches: no linked account found.",
            failed: "Failed to process vouch. Please try again later.",
            channelMessage: "vouched for",
            noDiscordLinked: "no discord linked",
            contextMenu: "Vouch Info",
            infoSent: "Vouch info sent to the vouch channel.",
            infoRequested: "here is the requested vouch info:",
            roleEarned: "has earned the role"
        },
        commands: {
            vouch: {
                description: "Vouch for a user",
                userOption: "The user to vouch for",
                count: {
                    description: "Get vouch count for a user",
                    userOption: "The user to check"
                },
                roles: {
                    add: {
                        description: "Add a vouch role threshold",
                        roleOption: "The role to assign",
                        countOption: "Number of unique vouches required",
                        reply: {
                            title: "Vouch Roles",
                            success: "Vouch role added"
                        }
                    },
                    remove: {
                        description: "Remove a vouch role threshold",
                        roleOption: "The role to remove",
                        reply: {
                            title: "Vouch Roles",
                            success: "Vouch role removed",
                            notFound: "Vouch role not found"
                        }
                    },
                    list: {
                        description: "List all vouch role thresholds",
                        reply: {
                            title: "Vouch Roles",
                            empty: "No vouch roles configured"
                        }
                    }
                }
            },
            set: {
                description: "Set a channel mapping",
                mappingOption: "The channel type to map",
                channelOption: "The Discord channel to post in",
                reply: {
                    title: "Channel Mapping",
                    success: "Channel mapping set"
                }
            },
            remove: {
                description: "Remove a channel mapping",
                mappingOption: "The channel type to remove",
                reply: {
                    title: "Channel Mapping",
                    success: "Channel mapping removed",
                    notFound: "Channel mapping not found"
                }
            }
        },
        format: {
            seller: "Seller",
            host: "Host",
            buyer: "Buyer",
            vouches: "Vouches",
            mapType: {
                buyer: "Your Map",
                seller: "My Map",
                both: "Your or My Map"
            },
            titles: {
                bossKilling: "WTS Boss Killing",
                nightmareMaps: "WTS Nightmare Maps",
                fiveWay: "WTS 5-Way",
                campaignSkip: "WTS Campaign Skip",
                goldRotation: "WTS Gold Rotation",
                templeHost: "WTS Temple Host",
                challengeCompletion: "WTS Challenge Completion",
                bloodlines: "WTS Bloodlines",
                labyrinth: "WTS Labyrinth",
                benchCraft: "WTS Bench Craft",
                poe2PinnacleEncounters: "WTS Pinnacle Encounters",
                poe2CitadelBosses: "WTS Citadel Bosses",
                poe2AnomalyAndMapBosses: "WTS Anomaly & Map Bosses",
                poe2CampaignBosses: "WTS Campaign Bosses",
                poe2CampaignSkip: "WTS Campaign Skip",
                poe2AscendancyTrials: "WTS Ascendancy Trials",
                poe2CraftingServices: "WTS Crafting Services",
                wtbBossKilling: "WTB Boss Killing",
                wtbNightmareMaps: "WTB Nightmare Maps",
                wtbInvitations: "WTB Invitations",
                wtbBloodlines: "WTB Bloodlines",
                wtbLabyrinth: "WTB Labyrinth",
                wtbFiveWay: "WTB 5-Way",
                wtbCampaignSkip: "WTB Campaign Skip",
                wtbGoldRotation: "WTB Gold Rotation",
                wtbTempleHost: "WTB Temple Host",
                wtbChallengeCompletion: "WTB Challenge Completion",
                wtbBenchCraft: "WTB Bench Craft",
                wtbPinnacleEncounters: "WTB Pinnacle Encounters",
                wtbCitadelBosses: "WTB Citadel Bosses",
                wtbAnomalyAndMapBosses: "WTB Anomaly & Map Bosses",
                wtbCampaignBosses: "WTB Campaign Bosses",
                wtbAscendancyTrials: "WTB Ascendancy Trials",
                wtbCraftingServices: "WTB Crafting Services"
            },
            regions: "Preferred Regions",
            browseServices: "Browse services",
            listServices: "List services",
            whispers: {
                bossKilling: "Hi, I'd like to buy your boss killing service",
                nightmareMaps: "Hi, I'd like to buy your nightmare map service",
                fiveWay: "Hi, I'd like to join your 5-way run",
                campaignSkip: "Hi, I'd like to buy your campaign skip service",
                goldRotation: "Hi, I'd like to join your gold rotation",
                templeHost: "Hi, I'd like to use your temple room",
                challengeCompletion: "Hi, I'd like to buy your challenge completion service",
                bloodlines: "Hi, I'd like to buy your bloodlines service",
                labyrinth: "Hi, I'd like to buy your labyrinth carry",
                benchCraft: "Hi, I need your bench craft service",
                poe2PinnacleEncounters: "Hi, I'd like to buy your pinnacle encounter carry",
                poe2CitadelBosses: "Hi, I'd like to buy your citadel boss carry",
                poe2AnomalyAndMapBosses: "Hi, I'd like to buy your anomaly/map boss carry",
                poe2CampaignBosses: "Hi, I'd like to buy your campaign boss carry",
                poe2CampaignSkip: "Hi, I'd like to buy your campaign skip service",
                poe2AscendancyTrials: "Hi, I'd like to buy your ascendancy trial carry",
                poe2CraftingServices: "Hi, I'd like to buy your crafting service",
                wtbBossKilling: "Hi, I can do your boss killing service",
                wtbNightmareMaps: "Hi, I can run your nightmare maps",
                wtbInvitations: "Hi, I can do your invitations",
                wtbBloodlines: "Hi, I can do your bloodlines service",
                wtbLabyrinth: "Hi, I can run your labyrinth carry",
                wtbFiveWay: "Hi, I can host your 5-way",
                wtbCampaignSkip: "Hi, I can do your campaign skip",
                wtbGoldRotation: "Hi, I can host your gold rotation",
                wtbTempleHost: "Hi, I can host your temple",
                wtbChallengeCompletion: "Hi, I can do your challenge completion",
                wtbBenchCraft: "Hi, I can craft that for you",
                wtbPinnacleEncounters: "Hi, I can do your pinnacle encounters",
                wtbCitadelBosses: "Hi, I can do your citadel bosses",
                wtbAnomalyAndMapBosses: "Hi, I can do your anomaly/map bosses",
                wtbCampaignBosses: "Hi, I can do your campaign bosses",
                wtbAscendancyTrials: "Hi, I can run your ascendancy trials",
                wtbCraftingServices: "Hi, I can do your crafting"
            }
        }
    }
}
